### ISSUE TITLE
Wierd chat bug

### ISSUE THREAD

**Issue by Vrathos** [Kkthnx/KkthnxUI#7]
Havin 2 Problems so far wich occured with your UI:

In chat tabs some post appear with an [ at the beginning and an ] at the end.they become klickable and yellow. Seems to happen randomly even with my posts.
![wowscrnshot_091115_012524](https://cloud.githubusercontent.com/assets/14226181/9803563/03068bd0-5824-11e5-8f85-c329be6fd437.jpg)

2. Issue appears when using the transmog system.  when i try to click more than one item to transmog, an massive error wave is incomming and i cant use the transmog window anymore. i saw an undermine journal part at the end but disabling doesnt fix it.

3131x C stack overflow
[C]: ?
[C]: ?
[C]: in function `Hide'
[string "*:OnLeave"]:1: in function <[string "*:OnLeave"]:1>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 inspectRequestSent = true
 SetTradePlayerItem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 updateTooltip = 0.035999989882112
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 comparing = false
 SetLootRollItem = <function> defined =[C]:-1
 inspectCache = <table> {
 }
 inspectRefresh = false
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetGlyph = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
 = <function> defined =[C]:-1
 = <function> defined @TheUndermineJournal\TheUndermineJournal.lua:274

**Comment by Kkthnx** [comment]
This should be resolved with https://github.com/Kkthnx/KkthnxUI/commit/6f0fd9c762208aa21c653351b0415ec41de7e42f

**Comment by Vrathos** [comment]
clean isntalled your ui. and disabled every other addon step by step. after disabling every addon but yours, both problems still occur

**Comment by Vrathos** [comment]
also got a new error

115x ...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:51: [string "safecall Dispatcher[2]"]:1: chunk has too many syntax levels
[C]: ?
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:51: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:55: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:54>
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
!BugGrabber\BugGrabber.lua:149: in function <!BugGrabber\BugGrabber.lua:147>
!BugGrabber\BugGrabber.lua:370: in function <!BugGrabber\BugGrabber.lua:292>
[C]: in function `(for generator)'
KkthnxUI\Core\Border.lua:12: in function `SetBorderColor'
KkthnxUI\Modules\Skins\Character-Charakter.lua:9: in function <KkthnxUI\Modules\Skins\Character.lua:8>
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
[C]: in function `SetVertexColor'
FrameXML\EquipmentFlyout.lua:396: in function <FrameXML\EquipmentFlyout.lua:370>
[C]: ?
[C]: in function `EquipmentFlyout_DisplayButton'
FrameXML\EquipmentFlyout.lua:245: in function `EquipmentFlyout_UpdateItems'
FrameXML\EquipmentFlyout.lua:186: in function <FrameXML\EquipmentFlyout.lua:134>
[C]: in function `EquipmentFlyout_Show'
FrameXML\EquipmentFlyout.lua:494: in function `EquipmentFlyout_UpdateFlyout'
FrameXML\EquipmentFlyout.lua:81: in function <FrameXML\EquipmentFlyout.lua:76>

Locals:
argCount = 2
code = "	local next, xpcall, eh = ...

	local method, arg1, arg2
	local function call() method(arg1, arg2) end

	local function dispatch(handlers, ...)
		local index
		index, method = next(handlers)
		if not method then return end
		local old_arg1, old_arg2 = arg1, arg2
		arg1, arg2 = ...
		repeat
			xpcall(call, eh)
			index, method = next(handlers, index)
		until not method
		arg1, arg2 = old_arg1, old_arg2
	end

	return dispatch
	"
ARGS = <table> {
 1 = "arg1"
 2 = "arg2"
}
OLD_ARGS = <table> {
 1 = "old_arg1"
 2 = "old_arg2"
}
tconcat = <function> defined =[C]:-1
assert = <function> defined =[C]:-1
loadstring = <function> defined =[C]:-1
next = <function> defined =[C]:-1
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:21

**Comment by Vrathos** [comment]
12x C stack overflow
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
[C]: ?
[C]: in function `SetVertexColor'
FrameXML\EquipmentFlyout.lua:396: in function <FrameXML\EquipmentFlyout.lua:370>
[C]: ?
[C]: in function `EquipmentFlyout_DisplayButton'
FrameXML\EquipmentFlyout.lua:245: in function `EquipmentFlyout_UpdateItems'
FrameXML\EquipmentFlyout.lua:186: in function <FrameXML\EquipmentFlyout.lua:134>
[C]: in function `EquipmentFlyout_Show'
FrameXML\EquipmentFlyout.lua:549: in function <FrameXML\EquipmentFlyout.lua:541>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 SetVertexColor = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
}
(*temporary) = 0.78431
(*temporary) = 0.27059
(*temporary) = 0.98039
 = <function> defined =[C]:-1
 = <function> defined @KkthnxUI\Modules\Skins\Character.lua:8

**Comment by Vrathos** [comment]
52x ...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:51: [string "safecall Dispatcher[2]"]:1: chunk has too many syntax levels
[C]: ?
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:51: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:55: in function <...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:54>
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
!BugGrabber\BugGrabber.lua:149: in function <!BugGrabber\BugGrabber.lua:147>
!BugGrabber\BugGrabber.lua:370: in function <!BugGrabber\BugGrabber.lua:292>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
[C]: ?
[C]: in function `SetVertexColor'
FrameXML\EquipmentFlyout.lua:396: in function <FrameXML\EquipmentFlyout.lua:370>
[C]: ?
[C]: in function `EquipmentFlyout_DisplayButton'
FrameXML\EquipmentFlyout.lua:245: in function `EquipmentFlyout_UpdateItems'
FrameXML\EquipmentFlyout.lua:186: in function <FrameXML\EquipmentFlyout.lua:134>
[C]: in function `EquipmentFlyout_Show'
FrameXML\EquipmentFlyout.lua:549: in function <FrameXML\EquipmentFlyout.lua:541>

Locals:
argCount = 2
code = "	local next, xpcall, eh = ...

	local method, arg1, arg2
	local function call() method(arg1, arg2) end

	local function dispatch(handlers, ...)
		local index
		index, method = next(handlers)
		if not method then return end
		local old_arg1, old_arg2 = arg1, arg2
		arg1, arg2 = ...
		repeat
			xpcall(call, eh)
			index, method = next(handlers, index)
		until not method
		arg1, arg2 = old_arg1, old_arg2
	end

	return dispatch
	"
ARGS = <table> {
 1 = "arg1"
 2 = "arg2"
}
OLD_ARGS = <table> {
 1 = "old_arg1"
 2 = "old_arg2"
}
tconcat = <function> defined =[C]:-1
assert = <function> defined =[C]:-1
loadstring = <function> defined =[C]:-1
next = <function> defined =[C]:-1
xpcall = <function> defined =[C]:-1
errorhandler = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:21

**Comment by Kkthnx** [comment]
Try the latest build now. Should be fixed with https://github.com/Kkthnx/KkthnxUI/commit/c29b4ac4af9cd7cee55f4cfaddccf500601968a2

The skinned char frame was never suppose to stay. I completely forgot about it. It is removed now.

**Comment by Vrathos** [comment]
transmog bug is fixed now :D 

chat bug still persists but il just disable the chatmodule for now. 
thx for your effort man

**Comment by Vrathos** [comment]
ok i could locate the chat bug source: it has something to do with this feature in the contacts tab:

-UIConfigChatDamage_meter_spam

did a couple of testruns and disabling this feature "fixes" it

**Comment by Kkthnx** [comment]
Okay I think I have it fixed will test and push in a bit! Thank you so much for testing this and getting down to a module that might be causing the issue!

**Comment by Vrathos** [comment]
Actually was fun to find the bug because i realy love the ui so far. Always glad to help such an dedicated UI developer. Keep up your good work!

**Comment by Vrathos** [comment]
dang it! had a new error ^^

7x KkthnxUI\Modules\Quests\ObjectiveTracker.lua:30: Usage: <unnamed>:SetSize(width, height)
[C]: in function `SetSize'
KkthnxUI\Modules\Quests\ObjectiveTracker.lua:30: in function <KkthnxUI\Modules\Quests\ObjectiveTracker.lua:26>
[C]: in function `SetBlockHeader'
..._ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua:444: in function `Update'
...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1014: in function `ObjectiveTracker_Update'
...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:638: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:612>
[C]: in function `AddQuestWatch'
...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:623: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:612>

Locals:
_ = <table> {
 OnFreeBlock = <function> defined @Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua:10
 OnBlockHeaderClick = <function> defined @Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua:75
 OnFreeTypedLine = <function> defined @Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua:21
 freeItemButtons = <table> {
 }
 hasSkippedBlocks = false
 Update = <function> defined @Blizzard_ObjectiveTracker\Blizzard_QuestObjectiveTracker.lua:407
 contentsAnimHeight = 68.000094413757
 updateReasonEvents = 3
 contentsHeight = 78.000094413757
 Header = <unnamed> {
 }
 usedBlocks = <table> {
 }
 oldContentsHeight = 127.00018882751
 firstBlock = <unnamed> {
 }
 SetBlockHeader = <function> defined =[C]:-1
 updateReasonModule = 256
}
block = <unnamed> {
 0 = <userdata>
 lines = <table> {
 }
 id = 36911
 HeaderButton = ObjectiveTrackerBlocksFrameHeader {
 }
 lineWidth = 190.02222204208
 HeaderText = <unnamed> {
 }
 questLogIndex = 37
 used = true
 module = <table> {
 }
 height = 12.999999046326
 itemButton = <unnamed> {
 }
}
item = <unnamed> {
 NormalTexture = <unnamed> {
 }
 charges = 0
 count = 0
 Count = <unnamed> {
 }
 0 = <userdata>
 HotKey = <unnamed> {
 }
 rangeTimer = -1
 Cooldown = <unnamed> {
 }
 icon = <unnamed> {
 }
}
C = <table> {
 nameplate = <table> {
 }
 stats = <table> {
 }
 general = <table> {
 }
 media = <table> {
 }
 combattext = <table> {
 }
 minimap = <table> {
 }
 loot = <table> {
 }
 automation = <table> {
 }
 toppanel = <table> {
 }
 map = <table> {
 }
 tooltip = <table> {
 }
 font = <table> {
 }
 position = <table> {
 }
 announcements = <table> {
 }
 unitframe = <table> {
 }
 chat = <table> {
 }
 actionbar = <table> {
 }
 misc = <table> {
 }
 buffs = <table> {
 }
 error = <table> {
 }
 blizzard = <table> {
 }
}

**Comment by Kkthnx** [comment]
Alright just got home gonna work on these. Sorry for the delay!

**Comment by Vrathos** [comment]
quest bug seems to be fixed now
